- src/generate/endpoint/templates.js
This prevents future problems, but not current ones. But it should be good enough.
> fixes single quotes in mapping template; closes #52

- src/commands/run.js
- src/run/index.js
- test/run/index.js
> Warn user when using run with different node version than AWS Lambda

- docs.js
> Create docs against cli.js instead of global shep

- migration.md
- src/generate-function/templates.js
- src/util/load.js
> Revert "@wip Warn on missing description field"

- src/util/build-functions.js
- test/build/index.js
- test/helpers/exec.js
- test/new/index.js
We'll fail with output if webpack fails
Closes #112 
I wish I knew how to test this in the CI. Happy to add any kind of tests with some guidance.
> Ensure webpack failures are detected

- src/new/templates.js
Conform to standardjs linting with newlines and spacing
> Add shep to the generated shep package.json

- package.json
- src/run/index.js
> Add await syntax and use it for run

- src/new/templates.js
Also add some newlines in generated json files
closes #110
> Throw if missing a config file for the env

- README.md
- src/commands/run.js
- src/run/index.js
- src/util/load.js
- test/run/index-all.js
- test/run/index.js
> Run multiple functions

- src/deploy/index.js
@southpolesteve just want to verify that this is what you wanted
> print api url on deploy, closes #109

- README.md
- src/new/templates.js
- src/util/build-functions.js
- test/build/index-custom.js
> Build Command

- src/commands/build.js
> Remove built prompt

- src/run/index.js
i like this in file. more explicit that it's in dev
> adds default env vars for local dev

- README.md
- package.json
- src/deploy/index.js
- src/util/aws/lambda.js
- src/util/upload-functions.js
- test/deploy/index-no-api.js
- test/deploy/index-no-build.js
- test/deploy/index.js
- test/logs/index.js
Closes #196, #190, fixes some bugs in tests introduced
> Api console log

- src/generate-function/templates.js
> add new lines to event files and lambda.json

- package.json
- src/run/index.js
> mock aws lambda context locally with package

- README.md
Trailing spaces are intentional
> New project guide

- src/util/aws/api-gateway.js
> Add automatic retry to deploys

- package.json
> Upgrade babel_preset_env

- src/commands/run.js
- src/util/load.js
> Remove unnecessary async from load

- src/new/index.js
- src/util/modules/fs.js
- test/new/index-new-role.js
- test/new/index-prexisting-role.js
- test/new/index.js
> Alter shep new behavior to be less destructive

- src/commands/run.js
- src/util/load.js
Reverts bustle/shep#222
This was ill thought out, breaks a ton of stuff, and doesn't completely solve the issue it was meant to solve.
> Revert "Remove unnecessary async from load"

- package.json
- src/cli.js
- test/commands/index.js
- test/helpers/yargs.js
Hoping that this PR will also include some tests for command parsing once I figure that out
Also addresses #225
> Revert to previous version of yargs, closes #231

- package.json
- src/util/zip-dir.js
> Switch from archiver to zipit

- src/commands/run.js
- src/run/index.js
> Invert truncation of shep run

- DOCS.md
- src/build/index.js
- src/commands/build.js
- src/commands/config/list.js
- src/commands/config/remove.js
- src/commands/config/set.js
- src/commands/config/sync.js
- src/commands/doctor.js
- src/commands/generate/webpack.js
- src/config-list/index.js
- src/config-remove/index.js
- src/config-set/index.js
- src/config-sync/index.js
- src/deploy/index.js
- src/doctor/index.js
- src/generate-endpoint/index.js
- src/generate-function/index.js
- src/new/index.js
- src/pull/index.js
- src/push/index.js
- src/util/get-all-function-aliases.js
- src/util/get-function-envs.js
- test/commands/index.js
- test/config-sync/index-conflict.js
- test/config-sync/index.js
- test/doctor/index.js
A beginning to #258, takes care of a lot of the noisy logging.
> Add quiet by default to straight function calls

- src/commands/build.js
- src/commands/config/list.js
- src/commands/config/remove.js
- src/commands/config/set.js
- src/commands/config/sync.js
- src/commands/deploy.js
- src/commands/generate/endpoint.js
- src/commands/logs.js
- src/commands/push.js
- src/config-list/index.js
- src/config-sync/index.js
- src/deploy/index.js
- src/generate-endpoint/index.js
- src/new/index.js
- src/pull/index.js
- src/util/aws/api-gateway.js
- src/util/aws/cloudwatch-logs.js
- src/util/aws/lambda.js
- src/util/aws/s3.js
- src/util/errors.js
- src/util/load.js
- src/util/reporter.js
- test/commands/index.js
Ended up fixing #260 during this
> Formalize errors

- DOCS.md
- README.md
- src/commands/generate/function.js
- src/commands/run.js
- src/run/index.js
- src/util/load.js
- src/util/upload-builds.js
- src/util/upload-functions.js
- test/run/index-all.js
- test/run/index-build.js
- test/run/index.js
> Make 'dist' configurable.

- src/util/aws/lambda.js
- src/util/upload-environment.js
- formalize some errors
- fix creating new functions
- fix creating new aliases
> Fix creating aliases

- DOCS.md
- src/commands/deploy.js
- src/deploy/index.js
Closes #296
Unsure what needs to be deployed re: permissions
> Add support for deploying without API

- src/util/aws/lambda.js
- src/util/upload-functions.js
Resolves issue reported in #297
> Fix logic for new aliases on existing functions

- src/util/aws/api-gateway.js
API gateway looks like is changed the acceptable options for the export API call
> Fix shep pull

- LICENSE
- package.json
> Create LICENSE text file and republish as MIT
